### ISSUE TITLE
required copy step not documented

### ISSUE THREAD

**Issue by ThorstenHans** [ManuelRauber/systemjs-bundler-prototype#1]
In order to get that working, you've to copy the `dist/terminal2` folder into `node_modules` or use npm link when using it in dedicated project folder.

**Comment by ManuelRauber** [comment]
Would you create a PR, since you already fixed it?

**Comment by ThorstenHans** [comment]
yeah will do so, as soon as Linux Kernel is feature complete

**Comment by ManuelRauber** [comment]
Dang

**Comment by ThorstenHans** [comment]
seriously, will do so when back from business trip
